// Mock data for the chat application
export const mockRooms = [
  {
    id: "general",
    name: "general",
    type: "channel" as const,
    unreadCount: 3,
  },
  {
    id: "random",
    name: "random",
    type: "channel" as const,
  },
  {
    id: "development",
    name: "development",
    type: "channel" as const,
    unreadCount: 1,
  },
  {
    id: "design",
    name: "design",
    type: "channel" as const,
  },
  {
    id: "dm-alice",
    name: "Alice Johnson",
    type: "direct" as const,
    unreadCount: 2,
  },
  {
    id: "dm-bob",
    name: "Bob Smith",
    type: "direct" as const,
  },
  {
    id: "dm-charlie",
    name: "Charlie Brown",
    type: "direct" as const,
  },
]


export const mockMessages = [
  {
    id: "1",
    content: "Hey everyone! Welcome to the general channel. Feel free to introduce yourselves here.",
    sender: "Alice Johnson",
    timestamp: "2024-01-15T09:00:00Z",
    roomId: "general",
  },
  {
    id: "2",
    content: "Thanks Alice! I'm Bob, excited to be part of the team.",
    sender: "Bob Smith",
    timestamp: "2024-01-15T09:05:00Z",
    roomId: "general",
  },
  {
    id: "3",
    content: "Hello everyone! Charlie here, looking forward to working with you all.",
    sender: "Charlie Brown",
    timestamp: "2024-01-15T09:10:00Z",
    roomId: "general",
  },
  {
    id: "4",
    content: "Welcome to the team! 🎉",
    sender: "Diana Prince",
    timestamp: "2024-01-15T09:15:00Z",
    roomId: "general",
  },
  {
    id: "5",
    content: "Has anyone started working on the new feature yet?",
    sender: "Alice Johnson",
    timestamp: "2024-01-15T10:00:00Z",
    roomId: "development",
  },
  {
    id: "6",
    content: "I'm planning to start this afternoon. Want to pair program?",
    sender: "Bob Smith",
    timestamp: "2024-01-15T10:05:00Z",
    roomId: "development",
  },
  {
    id: "7",
    content: "Count me in! I can help with the backend integration.",
    sender: "Frank Miller",
    timestamp: "2024-01-15T10:10:00Z",
    roomId: "development",
  },
  {
    id: "8",
    content: "Hey Bob! Are you free for a quick call?",
    sender: "Alice Johnson",
    timestamp: "2024-01-15T11:00:00Z",
    roomId: "dm-bob",
  },
  {
    id: "9",
    content: "Give me 5 minutes to finish this up.",
    sender: "Bob Smith",
    timestamp: "2024-01-15T11:02:00Z",
    roomId: "dm-bob",
  },
  {
    id: "10",
    content: "Perfect, no rush!",
    sender: "Alice Johnson",
    timestamp: "2024-01-15T11:03:00Z",
    roomId: "dm-bob",
  },
  {
    id: "11",
    content: "Did anyone see the latest design mockups?",
    sender: "Diana Prince",
    timestamp: "2024-01-15T14:00:00Z",
    roomId: "general",
  },
  {
    id: "12",
    content: "Yes! They look amazing. The new color scheme is much better.",
    sender: "Charlie Brown",
    timestamp: "2024-01-15T14:05:00Z",
    roomId: "general",
  },
  {
    id: "13",
    content: "I agree! The cyan and green palette works really well together.",
    sender: "Eve Wilson",
    timestamp: "2024-01-15T14:10:00Z",
    roomId: "general",
  },
  {
    id: "14",
    content: "Anyone up for lunch? There's a new place downtown.",
    sender: "Charlie Brown",
    timestamp: "2024-01-15T12:00:00Z",
    roomId: "random",
  },
  {
    id: "15",
    content: "I'm in! What kind of food?",
    sender: "Eve Wilson",
    timestamp: "2024-01-15T12:05:00Z",
    roomId: "random",
  },
  {
    id: "16",
    content: "Mediterranean! They have great reviews.",
    sender: "Charlie Brown",
    timestamp: "2024-01-15T12:07:00Z",
    roomId: "random",
  },
  {
    id: "17",
    content: "The new logo concepts are ready for review. Check your email!",
    sender: "Diana Prince",
    timestamp: "2024-01-15T15:00:00Z",
    roomId: "design",
  },
  {
    id: "18",
    content: "Thanks Diana! I'll take a look this afternoon.",
    sender: "Alice Johnson",
    timestamp: "2024-01-15T15:05:00Z",
    roomId: "design",
  },
  {
    id: "19",
    content: "Hey Charlie! How's the project going?",
    sender: "Alice Johnson",
    timestamp: "2024-01-15T16:00:00Z",
    roomId: "dm-charlie",
  },
  {
    id: "20",
    content: "Pretty good! Just finished the wireframes. Want to see?",
    sender: "Charlie Brown",
    timestamp: "2024-01-15T16:05:00Z",
    roomId: "dm-charlie",
  },
]

export const mockNotifications = [
  {
    id: "1",
    type: "message" as const,
    title: "New message in #general",
    content: "Alice Johnson: Did anyone see the latest design mockups?",
    timestamp: "2024-01-15T14:00:00Z",
    read: false,
  },
  {
    id: "2",
    type: "user_joined" as const,
    title: "User joined",
    content: "Eve Wilson joined the workspace",
    timestamp: "2024-01-15T13:30:00Z",
    read: false,
  },
  {
    id: "3",
    type: "message" as const,
    title: "5 new messages while you were offline",
    content: "You have unread messages in #development and #general",
    timestamp: "2024-01-15T12:00:00Z",
    read: true,
  },
  {
    id: "4",
    type: "system" as const,
    title: "System maintenance",
    content: "Scheduled maintenance will occur tonight at 2 AM EST",
    timestamp: "2024-01-15T10:00:00Z",
    read: true,
  },
  {
    id: "5",
    type: "mention" as const,
    title: "You were mentioned",
    content: "Bob Smith mentioned you in #development",
    timestamp: "2024-01-15T09:45:00Z",
    read: true,
  },
]
